export interface Province {
  value: string;
  labelEn: string;
  labelTh: string;
}

export const THAI_PROVINCES: Province[] = [
  { value: "amnat_charoen", labelEn: "Amnat Charoen", labelTh: "อำนาจเจริญ" },
  { value: "ang_thong", labelEn: "Ang Thong", labelTh: "อ่างทอง" },
  { value: "bangkok", labelEn: "Bangkok", labelTh: "กรุงเทพมหานคร" },
  { value: "bueng_kan", labelEn: "Bueng Kan", labelTh: "บึงกาฬ" },
  { value: "buri_ram", labelEn: "Buri Ram", labelTh: "บุรีรัมย์" },
  { value: "chachoengsao", labelEn: "Chachoengsao", labelTh: "ฉะเชิงเทรา" },
  { value: "chai_nat", labelEn: "Chai Nat", labelTh: "ชัยนาท" },
  { value: "chaiyaphum", labelEn: "Chaiyaphum", labelTh: "ชัยภูมิ" },
  { value: "chanthaburi", labelEn: "Chanthaburi", labelTh: "จันทบุรี" },
  { value: "chiang_mai", labelEn: "Chiang Mai", labelTh: "เชียงใหม่" },
  { value: "chiang_rai", labelEn: "Chiang Rai", labelTh: "เชียงราย" },
  { value: "chon_buri", labelEn: "Chon Buri", labelTh: "ชลบุรี" },
  { value: "chumphon", labelEn: "Chumphon", labelTh: "ชุมพร" },
  { value: "kalasin", labelEn: "Kalasin", labelTh: "กาฬสินธุ์" },
  { value: "kamphaeng_phet", labelEn: "Kamphaeng Phet", labelTh: "กำแพงเพชร" },
  { value: "kanchanaburi", labelEn: "Kanchanaburi", labelTh: "กาญจนบุรี" },
  { value: "khon_kaen", labelEn: "Khon Kaen", labelTh: "ขอนแก่น" },
  { value: "krabi", labelEn: "Krabi", labelTh: "กระบี่" },
  { value: "lampang", labelEn: "Lampang", labelTh: "ลำปาง" },
  { value: "lamphun", labelEn: "Lamphun", labelTh: "ลำพูน" },
  { value: "loei", labelEn: "Loei", labelTh: "เลย" },
  { value: "lop_buri", labelEn: "Lop Buri", labelTh: "ลพบุรี" },
  { value: "mae_hong_son", labelEn: "Mae Hong Son", labelTh: "แม่ฮ่องสอน" },
  { value: "maha_sarakham", labelEn: "Maha Sarakham", labelTh: "มหาสารคาม" },
  { value: "mukdahan", labelEn: "Mukdahan", labelTh: "มุกดาหาร" },
  { value: "nakhon_nayok", labelEn: "Nakhon Nayok", labelTh: "นครนายก" },
  { value: "nakhon_pathom", labelEn: "Nakhon Pathom", labelTh: "นครปฐม" },
  { value: "nakhon_phanom", labelEn: "Nakhon Phanom", labelTh: "นครพนม" },
  { value: "nakhon_ratchasima", labelEn: "Nakhon Ratchasima", labelTh: "นครราชสีมา" },
  { value: "nakhon_sawan", labelEn: "Nakhon Sawan", labelTh: "นครสวรรค์" },
  { value: "nakhon_si_thammarat", labelEn: "Nakhon Si Thammarat", labelTh: "นครศรีธรรมราช" },
  { value: "nan", labelEn: "Nan", labelTh: "น่าน" },
  { value: "narathiwat", labelEn: "Narathiwat", labelTh: "นราธิวาส" },
  { value: "nong_bua_lam_phu", labelEn: "Nong Bua Lam Phu", labelTh: "หนองบัวลำภู" },
  { value: "nong_khai", labelEn: "Nong Khai", labelTh: "หนองคาย" },
  { value: "nonthaburi", labelEn: "Nonthaburi", labelTh: "นนทบุรี" },
  { value: "pathum_thani", labelEn: "Pathum Thani", labelTh: "ปทุมธานี" },
  { value: "pattani", labelEn: "Pattani", labelTh: "ปัตตานี" },
  { value: "phang_nga", labelEn: "Phang Nga", labelTh: "พังงา" },
  { value: "phatthalung", labelEn: "Phatthalung", labelTh: "พัทลุง" },
  { value: "phayao", labelEn: "Phayao", labelTh: "พะเยา" },
  { value: "phetchabun", labelEn: "Phetchabun", labelTh: "เพชรบูรณ์" },
  { value: "phetchaburi", labelEn: "Phetchaburi", labelTh: "เพชรบุรี" },
  { value: "phichit", labelEn: "Phichit", labelTh: "พิจิตร" },
  { value: "phitsanulok", labelEn: "Phitsanulok", labelTh: "พิษณุโลก" },
  { value: "phra_nakhon_si_ayutthaya", labelEn: "Phra Nakhon Si Ayutthaya", labelTh: "พระนครศรีอยุธยา" },
  { value: "phrae", labelEn: "Phrae", labelTh: "แพร่" },
  { value: "phuket", labelEn: "Phuket", labelTh: "ภูเก็ต" },
  { value: "prachin_buri", labelEn: "Prachin Buri", labelTh: "ปราจีนบุรี" },
  { value: "prachuap_khiri_khan", labelEn: "Prachuap Khiri Khan", labelTh: "ประจวบคีรีขันธ์" },
  { value: "ranong", labelEn: "Ranong", labelTh: "ระนอง" },
  { value: "ratchaburi", labelEn: "Ratchaburi", labelTh: "ราชบุรี" },
  { value: "rayong", labelEn: "Rayong", labelTh: "ระยอง" },
  { value: "roi_et", labelEn: "Roi Et", labelTh: "ร้อยเอ็ด" },
  { value: "sa_kaeo", labelEn: "Sa Kaeo", labelTh: "สระแก้ว" },
  { value: "sakon_nakhon", labelEn: "Sakon Nakhon", labelTh: "สกลนคร" },
  { value: "samut_prakan", labelEn: "Samut Prakan", labelTh: "สมุทรปราการ" },
  { value: "samut_sakhon", labelEn: "Samut Sakhon", labelTh: "สมุทรสาคร" },
  { value: "samut_songkhram", labelEn: "Samut Songkhram", labelTh: "สมุทรสงคราม" },
  { value: "saraburi", labelEn: "Saraburi", labelTh: "สระบุรี" },
  { value: "satun", labelEn: "Satun", labelTh: "สตูล" },
  { value: "si_sa_ket", labelEn: "Si Sa Ket", labelTh: "ศรีสะเกษ" },
  { value: "sing_buri", labelEn: "Sing Buri", labelTh: "สิงห์บุรี" },
  { value: "songkhla", labelEn: "Songkhla", labelTh: "สงขลา" },
  { value: "sukhothai", labelEn: "Sukhothai", labelTh: "สุโขทัย" },
  { value: "suphan_buri", labelEn: "Suphan Buri", labelTh: "สุพรรณบุรี" },
  { value: "surat_thani", labelEn: "Surat Thani", labelTh: "สุราษฎร์ธานี" },
  { value: "surin", labelEn: "Surin", labelTh: "สุรินทร์" },
  { value: "tak", labelEn: "Tak", labelTh: "ตาก" },
  { value: "trang", labelEn: "Trang", labelTh: "ตรัง" },
  { value: "trat", labelEn: "Trat", labelTh: "ตราด" },
  { value: "ubon_ratchathani", labelEn: "Ubon Ratchathani", labelTh: "อุบลราชธานี" },
  { value: "udon_thani", labelEn: "Udon Thani", labelTh: "อุดรธานี" },
  { value: "uthai_thani", labelEn: "Uthai Thani", labelTh: "อุทัยธานี" },
  { value: "uttaradit", labelEn: "Uttaradit", labelTh: "อุตรดิตถ์" },
  { value: "yala", labelEn: "Yala", labelTh: "ยะลา" },
  { value: "yasothon", labelEn: "Yasothon", labelTh: "ยโสธร" },
];

/** Look up a province by its value key and return the display label for the given locale */
export function getProvinceLabel(value: string, locale: string = "th"): string {
  const province = THAI_PROVINCES.find((p) => p.value === value);
  if (!province) return value;
  return locale === "th" ? province.labelTh : province.labelEn;
}
