export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type BookingStatus =
  | "pending"
  | "verified"
  | "confirmed"
  | "rejected"
  | "cancelled"
  | "completed";

export interface Database {
  public: {
    Tables: {
      hosts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          email: string;
          phone: string | null;
          promptpay_id: string;
          line_user_id: string | null;
          line_channel_access_token: string | null;
          deposit_amount: number;
          deposit_by_month: Record<string, number> | null;
          cancellation_days: number;
          notification_preference: string;
          security_pin_hash: string | null;
          status: string;
          is_verified: boolean;
          avatar_url: string | null;
          bank_name: string | null;
          bank_account_number: string | null;
          bank_account_name: string | null;
          payment_display: string;
          require_otp: boolean;
          plan_type: string;
          plan_free_expires_at: string | null;
          plan_pending_type: string | null;
          plan_pending_effective_at: string | null;
          wallet_balance: number;
          wallet_credit_limit: number;
          wallet_negative_since: string | null;
          wallet_low_notified_at: string | null;
          commission_pct_override: number | null;
          fixed_rate_override: number | null;
          fixed_rate_term_months: number | null;
          fixed_rate_term_started_at: string | null;
          fixed_rate_term_ends_at: string | null;
          plan_pending_term_months: number | null;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          email: string;
          phone?: string | null;
          promptpay_id: string;
          line_user_id?: string | null;
          line_channel_access_token?: string | null;
          deposit_amount?: number;
          deposit_by_month?: Record<string, number> | null;
          cancellation_days?: number;
          notification_preference?: string;
          security_pin_hash?: string | null;
          status?: string;
          is_verified?: boolean;
          avatar_url?: string | null;
          bank_name?: string | null;
          bank_account_number?: string | null;
          bank_account_name?: string | null;
          payment_display?: string;
          require_otp?: boolean;
          plan_type?: string;
          plan_free_expires_at?: string | null;
          plan_pending_type?: string | null;
          plan_pending_effective_at?: string | null;
          wallet_balance?: number;
          wallet_credit_limit?: number;
          wallet_negative_since?: string | null;
          wallet_low_notified_at?: string | null;
          commission_pct_override?: number | null;
          fixed_rate_override?: number | null;
          fixed_rate_term_months?: number | null;
          fixed_rate_term_started_at?: string | null;
          fixed_rate_term_ends_at?: string | null;
          plan_pending_term_months?: number | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          promptpay_id?: string;
          line_user_id?: string | null;
          line_channel_access_token?: string | null;
          deposit_amount?: number;
          deposit_by_month?: Record<string, number> | null;
          cancellation_days?: number;
          notification_preference?: string;
          security_pin_hash?: string | null;
          status?: string;
          is_verified?: boolean;
          avatar_url?: string | null;
          bank_name?: string | null;
          bank_account_number?: string | null;
          bank_account_name?: string | null;
          payment_display?: string;
          require_otp?: boolean;
          plan_type?: string;
          plan_free_expires_at?: string | null;
          plan_pending_type?: string | null;
          plan_pending_effective_at?: string | null;
          wallet_balance?: number;
          wallet_credit_limit?: number;
          wallet_negative_since?: string | null;
          wallet_low_notified_at?: string | null;
          commission_pct_override?: number | null;
          fixed_rate_override?: number | null;
          fixed_rate_term_months?: number | null;
          fixed_rate_term_started_at?: string | null;
          fixed_rate_term_ends_at?: string | null;
          plan_pending_term_months?: number | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      homestays: {
        Row: {
          id: string;
          host_id: string;
          slug: string;
          name: string;
          description: string;
          tagline: string | null;
          location: string;
          map_embed_url: string | null;
          max_guests: number;
          amenities: string[];
          prohibitions: string[];
          check_in_time: string | null;
          check_out_time: string | null;
          hero_image_url: string | null;
          logo_url: string | null;
          gallery: string[];
          theme_color: string;
          is_active: boolean;
          facebook_url: string | null;
          tiktok_url: string | null;
          instagram_url: string | null;
          line_id: string | null;
          check_in_info: string | null;
          policies: string | null;
          faq: { question: string; answer: string }[];
          promo_codes_enabled: boolean;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          host_id: string;
          slug: string;
          name: string;
          description: string;
          tagline?: string | null;
          location: string;
          map_embed_url?: string | null;
          max_guests?: number;
          amenities?: string[];
          prohibitions?: string[];
          check_in_time?: string | null;
          check_out_time?: string | null;
          hero_image_url?: string | null;
          logo_url?: string | null;
          gallery?: string[];
          theme_color?: string;
          is_active?: boolean;
          facebook_url?: string | null;
          tiktok_url?: string | null;
          instagram_url?: string | null;
          line_id?: string | null;
          check_in_info?: string | null;
          policies?: string | null;
          faq?: { question: string; answer: string }[];
          promo_codes_enabled?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          host_id?: string;
          slug?: string;
          name?: string;
          description?: string;
          tagline?: string | null;
          location?: string;
          map_embed_url?: string | null;
          max_guests?: number;
          amenities?: string[];
          prohibitions?: string[];
          check_in_time?: string | null;
          check_out_time?: string | null;
          hero_image_url?: string | null;
          logo_url?: string | null;
          gallery?: string[];
          theme_color?: string;
          is_active?: boolean;
          facebook_url?: string | null;
          tiktok_url?: string | null;
          instagram_url?: string | null;
          line_id?: string | null;
          check_in_info?: string | null;
          policies?: string | null;
          faq?: { question: string; answer: string }[];
          promo_codes_enabled?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      rooms: {
        Row: {
          id: string;
          homestay_id: string;
          name: string;
          description: string | null;
          price_per_night: number;
          max_guests: number;
          quantity: number;
          images: string[];
          is_active: boolean;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          homestay_id: string;
          name: string;
          description?: string | null;
          price_per_night: number;
          max_guests?: number;
          quantity?: number;
          images?: string[];
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string;
          name?: string;
          description?: string | null;
          price_per_night?: number;
          max_guests?: number;
          quantity?: number;
          images?: string[];
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      room_options: {
        Row: {
          id: string;
          room_id: string;
          name: string;
          price: number;
          pricing_type: 'per_night' | 'per_time';
          sort_order: number;
          is_active: boolean;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          name: string;
          price: number;
          pricing_type?: 'per_night' | 'per_time';
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          name?: string;
          price?: number;
          pricing_type?: 'per_night' | 'per_time';
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      room_guest_pricing: {
        Row: {
          id: string;
          room_id: string;
          adults: number;
          children: number;
          detail: string | null;
          surcharge: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          adults?: number;
          children?: number;
          detail?: string | null;
          surcharge?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          adults?: number;
          children?: number;
          detail?: string | null;
          surcharge?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          homestay_id: string;
          room_id: string | null;
          guest_name: string;
          guest_email: string;
          guest_phone: string;
          guest_province: string | null;
          check_in: string;
          check_out: string;
          num_guests: number;
          total_price: number;
          discount_amount: number;
          status: BookingStatus;
          payment_slip_url: string | null;
          easyslip_verified: boolean;
          easyslip_response: Json | null;
          payment_slip_hash: string | null;
          slip_trans_ref: string | null;
          notes: string | null;
          payment_type: string;
          amount_paid: number;
          checked_in_at: string | null;
          checked_out_at: string | null;
          cancelled_by: string | null;
          cancelled_at: string | null;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
          selected_options: Json;
          booking_source: string;
          guest_pricing_label: string | null;
          guest_pricing_surcharge: number;
          group_id: string | null;
        };
        Insert: {
          id?: string;
          homestay_id: string;
          room_id?: string | null;
          group_id?: string | null;
          guest_name: string;
          guest_email: string;
          guest_phone: string;
          guest_line_id?: string | null;
          check_in: string;
          check_out: string;
          num_guests: number;
          total_price: number;
          discount_amount?: number;
          status?: BookingStatus;
          payment_slip_url?: string | null;
          easyslip_verified?: boolean;
          easyslip_response?: Json | null;
          payment_slip_hash?: string | null;
          slip_trans_ref?: string | null;
          notes?: string | null;
          payment_type?: string;
          amount_paid?: number;
          checked_in_at?: string | null;
          checked_out_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          selected_options?: Json;
          booking_source?: string;
          guest_pricing_label?: string | null;
          guest_pricing_surcharge?: number;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string;
          room_id?: string | null;
          group_id?: string | null;
          guest_name?: string;
          guest_email?: string;
          guest_phone?: string;
          guest_line_id?: string | null;
          check_in?: string;
          check_out?: string;
          num_guests?: number;
          total_price?: number;
          discount_amount?: number;
          status?: BookingStatus;
          payment_slip_url?: string | null;
          easyslip_verified?: boolean;
          easyslip_response?: Json | null;
          payment_slip_hash?: string | null;
          slip_trans_ref?: string | null;
          notes?: string | null;
          payment_type?: string;
          amount_paid?: number;
          checked_in_at?: string | null;
          checked_out_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          selected_options?: Json;
          booking_source?: string;
          guest_pricing_label?: string | null;
          guest_pricing_surcharge?: number;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      booking_groups: {
        Row: {
          id: string;
          homestay_id: string;
          guest_name: string;
          guest_email: string;
          guest_phone: string;
          guest_province: string | null;
          notes: string | null;
          total_price: number;
          discount_amount: number;
          payment_type: string;
          amount_paid: number;
          status: BookingStatus;
          easyslip_verified: boolean;
          payment_slip_url: string | null;
          payment_slip_hash: string | null;
          slip_trans_ref: string | null;
          easyslip_response: Json | null;
          booking_source: string;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          homestay_id: string;
          guest_name: string;
          guest_email: string;
          guest_phone: string;
          guest_province?: string | null;
          notes?: string | null;
          total_price?: number;
          discount_amount?: number;
          payment_type?: string;
          amount_paid?: number;
          status?: BookingStatus;
          easyslip_verified?: boolean;
          payment_slip_url?: string | null;
          payment_slip_hash?: string | null;
          slip_trans_ref?: string | null;
          easyslip_response?: Json | null;
          booking_source?: string;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string;
          guest_name?: string;
          guest_email?: string;
          guest_phone?: string;
          guest_province?: string | null;
          notes?: string | null;
          total_price?: number;
          discount_amount?: number;
          payment_type?: string;
          amount_paid?: number;
          status?: BookingStatus;
          easyslip_verified?: boolean;
          payment_slip_url?: string | null;
          payment_slip_hash?: string | null;
          slip_trans_ref?: string | null;
          easyslip_response?: Json | null;
          booking_source?: string;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      blocked_dates: {
        Row: {
          id: string;
          homestay_id: string;
          date: string;
          reason: string | null;
          room_id: string | null;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          homestay_id: string;
          date: string;
          reason?: string | null;
          room_id?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string;
          date?: string;
          reason?: string | null;
          room_id?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      booking_holds: {
        Row: {
          id: string;
          room_id: string;
          check_in: string;
          check_out: string;
          session_id: string;
          expires_at: string;
          created_at: string;
          guest_phone: string | null;
        };
        Insert: {
          id?: string;
          room_id: string;
          check_in: string;
          check_out: string;
          session_id: string;
          expires_at: string;
          created_at?: string;
          guest_phone?: string | null;
        };
        Update: {
          id?: string;
          room_id?: string;
          check_in?: string;
          check_out?: string;
          session_id?: string;
          expires_at?: string;
          created_at?: string;
          guest_phone?: string | null;
        };
      };
      reviews: {
        Row: {
          id: string;
          homestay_id: string;
          booking_id: string;
          guest_name: string;
          rating: number;
          comment: string | null;
          topic: string | null;
          rating_environment: number | null;
          rating_cleanliness: number | null;
          rating_service: number | null;
          rating_value: number | null;
          photos: string[];
          impression_tags: string[];
          would_return: string | null;
          stay_highlight: string | null;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          homestay_id: string;
          booking_id: string;
          guest_name: string;
          rating: number;
          comment?: string | null;
          topic?: string | null;
          rating_environment?: number | null;
          rating_cleanliness?: number | null;
          rating_service?: number | null;
          rating_value?: number | null;
          photos?: string[];
          impression_tags?: string[];
          would_return?: string | null;
          stay_highlight?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string;
          booking_id?: string;
          guest_name?: string;
          rating?: number;
          comment?: string | null;
          topic?: string | null;
          rating_environment?: number | null;
          rating_cleanliness?: number | null;
          rating_service?: number | null;
          rating_value?: number | null;
          photos?: string[];
          impression_tags?: string[];
          would_return?: string | null;
          stay_highlight?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      push_subscriptions: {
        Row: {
          id: string;
          host_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent: string | null;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          host_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          host_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          user_agent?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      login_otps: {
        Row: {
          id: string;
          email: string;
          code: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          code: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          code?: string;
          expires_at?: string;
          created_at?: string;
        };
      };
      room_seasonal_prices: {
        Row: {
          id: string;
          room_id: string;
          name: string;
          start_date: string;
          end_date: string;
          price_per_night: number;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          name: string;
          start_date: string;
          end_date: string;
          price_per_night: number;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          name?: string;
          start_date?: string;
          end_date?: string;
          price_per_night?: number;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      platform_admins: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          name: string;
          phone: string | null;
          promptpay_id: string | null;
          line_user_id: string | null;
          line_channel_access_token: string | null;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email: string;
          name: string;
          phone?: string | null;
          promptpay_id?: string | null;
          line_user_id?: string | null;
          line_channel_access_token?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          name?: string;
          phone?: string | null;
          promptpay_id?: string | null;
          line_user_id?: string | null;
          line_channel_access_token?: string | null;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      history_logs: {
        Row: {
          id: string;
          homestay_id: string | null;
          entity_type: string;
          entity_id: string;
          event_type: string;
          actor_type: string;
          actor_id: string | null;
          data: Json;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          homestay_id?: string | null;
          entity_type: string;
          entity_id: string;
          event_type: string;
          actor_type: string;
          actor_id?: string | null;
          data?: Json;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string | null;
          entity_type?: string;
          entity_id?: string;
          event_type?: string;
          actor_type?: string;
          actor_id?: string | null;
          data?: Json;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      platform_billing_config: {
        Row: {
          id: string;
          commission_pct: number;
          fixed_rate_amount: number;
          fixed_rate_term_tiers: FixedRateTermTier[];
          promptpay_id: string | null;
          bank_name: string | null;
          bank_account_number: string | null;
          bank_account_name: string | null;
          payment_display: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          commission_pct?: number;
          fixed_rate_amount?: number;
          fixed_rate_term_tiers?: FixedRateTermTier[];
          promptpay_id?: string | null;
          bank_name?: string | null;
          bank_account_number?: string | null;
          bank_account_name?: string | null;
          payment_display?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          commission_pct?: number;
          fixed_rate_amount?: number;
          fixed_rate_term_tiers?: FixedRateTermTier[];
          promptpay_id?: string | null;
          bank_name?: string | null;
          bank_account_number?: string | null;
          bank_account_name?: string | null;
          payment_display?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      wallet_transactions: {
        Row: {
          id: string;
          host_id: string;
          type: string;
          amount: number;
          balance_after: number;
          reference_id: string | null;
          description: string | null;
          slip_url: string | null;
          slip_hash: string | null;
          slip_trans_ref: string | null;
          easyslip_verified: boolean;
          easyslip_response: Json | null;
          status: string;
          created_at: string;
          created_by: string;
        };
        Insert: {
          id?: string;
          host_id: string;
          type: string;
          amount: number;
          balance_after: number;
          reference_id?: string | null;
          description?: string | null;
          slip_url?: string | null;
          slip_hash?: string | null;
          slip_trans_ref?: string | null;
          easyslip_verified?: boolean;
          easyslip_response?: Json | null;
          status?: string;
          created_at?: string;
          created_by?: string;
        };
        Update: {
          id?: string;
          host_id?: string;
          type?: string;
          amount?: number;
          balance_after?: number;
          reference_id?: string | null;
          description?: string | null;
          slip_url?: string | null;
          slip_hash?: string | null;
          slip_trans_ref?: string | null;
          easyslip_verified?: boolean;
          easyslip_response?: Json | null;
          status?: string;
          created_at?: string;
          created_by?: string;
        };
      };
      billing_retry_queue: {
        Row: {
          id: string;
          operation: string;
          booking_id: string;
          attempts: number;
          last_error: string | null;
          last_attempt_at: string | null;
          next_attempt_at: string;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          operation: string;
          booking_id: string;
          attempts?: number;
          last_error?: string | null;
          last_attempt_at?: string | null;
          next_attempt_at?: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          operation?: string;
          booking_id?: string;
          attempts?: number;
          last_error?: string | null;
          last_attempt_at?: string | null;
          next_attempt_at?: string;
          resolved_at?: string | null;
          created_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          host_id: string;
          amount: number;
          period_start: string;
          period_end: string;
          status: string;
          slip_url: string | null;
          slip_hash: string | null;
          slip_trans_ref: string | null;
          easyslip_verified: boolean;
          easyslip_response: Json | null;
          paid_at: string | null;
          due_date: string;
          term_months: number;
          discount_pct: number;
          created_at: string;
          updated_at: string;
          created_by: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          host_id: string;
          amount: number;
          period_start: string;
          period_end: string;
          status?: string;
          slip_url?: string | null;
          slip_hash?: string | null;
          slip_trans_ref?: string | null;
          easyslip_verified?: boolean;
          easyslip_response?: Json | null;
          paid_at?: string | null;
          due_date: string;
          term_months?: number;
          discount_pct?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          host_id?: string;
          amount?: number;
          period_start?: string;
          period_end?: string;
          status?: string;
          slip_url?: string | null;
          slip_hash?: string | null;
          slip_trans_ref?: string | null;
          easyslip_verified?: boolean;
          easyslip_response?: Json | null;
          paid_at?: string | null;
          due_date?: string;
          term_months?: number;
          discount_pct?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
      };
      promo_codes: {
        Row: {
          id: string;
          homestay_id: string;
          code: string;
          discount_type: "percentage" | "fixed";
          discount_value: number;
          recommender_name: string | null;
          recommender_phone: string | null;
          recommender_promptpay: string | null;
          recommender_note: string | null;
          commission_type: "percentage" | "fixed" | null;
          commission_value: number | null;
          start_at: string | null;
          expires_at: string | null;
          max_uses: number | null;
          times_used: number;
          one_use_per_guest: boolean;
          is_active: boolean;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          homestay_id: string;
          code: string;
          discount_type: "percentage" | "fixed";
          discount_value: number;
          recommender_name?: string | null;
          recommender_phone?: string | null;
          recommender_promptpay?: string | null;
          recommender_note?: string | null;
          commission_type?: "percentage" | "fixed" | null;
          commission_value?: number | null;
          start_at?: string | null;
          expires_at?: string | null;
          max_uses?: number | null;
          times_used?: number;
          one_use_per_guest?: boolean;
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          homestay_id?: string;
          code?: string;
          discount_type?: "percentage" | "fixed";
          discount_value?: number;
          recommender_name?: string | null;
          recommender_phone?: string | null;
          recommender_promptpay?: string | null;
          recommender_note?: string | null;
          commission_type?: "percentage" | "fixed" | null;
          commission_value?: number | null;
          start_at?: string | null;
          expires_at?: string | null;
          max_uses?: number | null;
          times_used?: number;
          one_use_per_guest?: boolean;
          is_active?: boolean;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      promo_redemptions: {
        Row: {
          id: string;
          promo_code_id: string;
          booking_id: string | null;
          group_id: string | null;
          discount_amount: number;
          commission_amount: number;
          payout_status: "pending" | "paid" | "cancelled";
          paid_at: string | null;
          paid_note: string | null;
          guest_phone: string;
          guest_email: string;
          created_at: string;
          created_by: string;
          updated_at: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          promo_code_id: string;
          booking_id?: string | null;
          group_id?: string | null;
          discount_amount: number;
          commission_amount?: number;
          payout_status?: "pending" | "paid" | "cancelled";
          paid_at?: string | null;
          paid_note?: string | null;
          guest_phone: string;
          guest_email: string;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          promo_code_id?: string;
          booking_id?: string | null;
          group_id?: string | null;
          discount_amount?: number;
          commission_amount?: number;
          payout_status?: "pending" | "paid" | "cancelled";
          paid_at?: string | null;
          paid_note?: string | null;
          guest_phone?: string;
          guest_email?: string;
          created_at?: string;
          created_by?: string;
          updated_at?: string;
          updated_by?: string;
        };
      };
      date_change_requests: {
        Row: {
          id: string;
          booking_id: string;
          old_check_in: string;
          old_check_out: string;
          new_check_in: string;
          new_check_out: string;
          old_total_price: number;
          new_total_price: number;
          new_discount_amount: number;
          price_difference: number;
          status: string;
          requested_by: string;
          slip_hash: string | null;
          slip_trans_ref: string | null;
          payment_slip_url: string | null;
          easyslip_response: Json | null;
          easyslip_verified: boolean;
          reject_reason: string | null;
          old_room_id: string | null;
          new_room_id: string | null;
          additional_payment: number;
          created_at: string;
          updated_at: string;
          created_by: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          old_check_in: string;
          old_check_out: string;
          new_check_in: string;
          new_check_out: string;
          old_total_price: number;
          new_total_price: number;
          new_discount_amount?: number;
          price_difference?: number;
          status?: string;
          requested_by: string;
          slip_hash?: string | null;
          slip_trans_ref?: string | null;
          payment_slip_url?: string | null;
          easyslip_response?: Json | null;
          easyslip_verified?: boolean;
          reject_reason?: string | null;
          old_room_id?: string | null;
          new_room_id?: string | null;
          additional_payment?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          old_check_in?: string;
          old_check_out?: string;
          new_check_in?: string;
          new_check_out?: string;
          old_total_price?: number;
          new_total_price?: number;
          new_discount_amount?: number;
          price_difference?: number;
          status?: string;
          requested_by?: string;
          slip_hash?: string | null;
          slip_trans_ref?: string | null;
          payment_slip_url?: string | null;
          easyslip_response?: Json | null;
          easyslip_verified?: boolean;
          reject_reason?: string | null;
          old_room_id?: string | null;
          new_room_id?: string | null;
          additional_payment?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
      };
    };
  };
}

export type Host = Database["public"]["Tables"]["hosts"]["Row"];
export type Homestay = Database["public"]["Tables"]["homestays"]["Row"];
export type Room = Database["public"]["Tables"]["rooms"]["Row"];
export type Booking = Database["public"]["Tables"]["bookings"]["Row"];
export type BookingGroup = Database["public"]["Tables"]["booking_groups"]["Row"];
export type BlockedDate = Database["public"]["Tables"]["blocked_dates"]["Row"];
export type BookingHold = Database["public"]["Tables"]["booking_holds"]["Row"];
export type Review = Database["public"]["Tables"]["reviews"]["Row"];
export type RoomSeasonalPrice = Database["public"]["Tables"]["room_seasonal_prices"]["Row"];
export type RoomOption = Database["public"]["Tables"]["room_options"]["Row"];
export type RoomGuestPricing = Database["public"]["Tables"]["room_guest_pricing"]["Row"];
export type PlatformAdmin = Database["public"]["Tables"]["platform_admins"]["Row"];
export type HistoryLog = Database["public"]["Tables"]["history_logs"]["Row"];
export type DateChangeRequest = Database["public"]["Tables"]["date_change_requests"]["Row"];
export type PlatformBillingConfig = Database["public"]["Tables"]["platform_billing_config"]["Row"];
export type WalletTransaction = Database["public"]["Tables"]["wallet_transactions"]["Row"];
export type Invoice = Database["public"]["Tables"]["invoices"]["Row"];
export type PromoCode = Database["public"]["Tables"]["promo_codes"]["Row"];
export type PromoRedemption = Database["public"]["Tables"]["promo_redemptions"]["Row"];

export type PlanType = "free" | "commission" | "fixed_rate";
export type PromoDiscountType = "percentage" | "fixed";
export type PromoPayoutStatus = "pending" | "paid" | "cancelled";

export interface FixedRateTermTier {
  months: number;
  discount_pct: number;
}
